---
name: Config-Augeas
version: 0.202
author:
  - Dominique Dumont (ddumont at cpan dot org)
abstract: Edit configuration files through Augeas C library
license: lgpl
resources:
  license: http://opensource.org/licenses/lgpl-license.php
dynamic_config: 1
provides:
  Config::Augeas:
    file: lib/Config/Augeas.pm
    version: 0.202
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
